[application]

# App (Project) Name
name = "Tailwind CSS + Dioxus"

# Dioxus App Default Platform
# Dioxus App Default Platform
default_platform = "fullstack"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Draws Notes"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file
#
style = ["/assets/tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# Javascript code file
script = []
